---
title: "template-prediction-model"
output: html_document
date: "`r format(Sys.time(), '%Y-%m-%d')`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

# Background
- **Author**: `<AUTHOR NAME>`
- **Created At**: `<YYYY-MM-DD>`
- **Path to Training Data：**
- **Path to Testing Data：**
- **Model Specification：**
    - Method：
    - Variables：
    - Tuning Parameters：
    - Optimization Method：
- **Main Findings and Takeaways：**
    - In-sample `<metric>`:
    - Out-sample `<metric>`:
- **Future Direciton：**

```{r}
# Load packages here
```

```{r}
# Load the TRAINING data here and please finish all the data manipulation here.
# Finish this block by printing the first ten observations of the data.
# Note:
# - You may only read data from /data/processed.
# - Files in /data/processed should already be cleaned and prepared for analysis.
# - Beyond simple filtering of observations or generating a small number of variables,
#   further data manipulation is not allowed. If more extensive changes are needed,
#   update the source data instead.
```

```{r}
# Load the TESTING data here and please finish all the data manipulation here.
# Finish this block by printing the first ten observations of the data.
```

### The actual modeling starts below
For the remaining blocks, make sure you have followed the guidelines as specified in 
[專案資料夾結構、檔案命名與文件規範](https://docs.google.com/document/d/1sl6gEFMdmiGsiNjLe17UmZ30xKxq15U0Mb2B-Jvusxg/edit?tab=t.33iie8ybx7s4).


```{r}
# Include the model specification here.  Please describe the model by stating, including
# type of method used, the variables included, the hyperparameters, and
# the method of optimization.
```

```{r}
```

```{r}
```

```{r}
# ---- AUTO-TRANSLATED (conservative) ----
# Report the performance metrics for training data in this block.
```

```{r}
# ---- AUTO-TRANSLATED (conservative) ----
# Report the performance metrics for testing data in this block.
```